apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations: {}
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: tbd
    app.kubernetes.io/instance: tbd
    app.kubernetes.io/managed-by: kpt
    app.kubernetes.io/name: nf-injector
    app.kubernetes.io/part-of: nf-injector
    app.kubernetes.io/version: tbd
  name: nf-injector-controller-porch-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nf-injector-controller-porch-role
subjects:
- kind: ServiceAccount
  name: nf-injector-controller
  namespace: injector
